apiVersion: v1
kind: Secret
metadata:
  name: promitor-scraper
  labels:
    chart: {{ template "promitor-scraper.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  PROMITOR_AUTH_APPKEY: {{ template "promitor-scraper.chart" . }}